version: "3.8"
name: angular-docker-nginx
services:
  frontend:
    container_name: angular-docker-nginx
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 80:80
    networks:
      - dockerize-net

networks:
  dockerize-net:
    driver: bridge
