version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 80:80
    networks:
      - dockerize-net

networks:
  dockerize-net:
    driver: bridge
